>>> from fastapi import FastAPI
... import requests
... 
... app = FastAPI()
... 
... @app.get("/")
... def home():
...     return {"message": "Patent search API running"}
... 
... @app.get("/search")
... def search(query: str):
... 
...     url = f"https://api.patentsview.org/patents/query?q={{\"_text_any\":{{\"patent_title\":\"{query}\"}}}}"
... 
...     response = requests.get(url)
...     data = response.json()
... 
...     patents = []
... 
...     for p in data["patents"][:10]:
...         patents.append({
...             "title": p["patent_title"],
...             "abstract": p.get("patent_abstract",""),
...             "number": p["patent_number"]
...         })
... 
